image: node:13.8

stages:
  - build
  - test

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  before_script:
    - apt-get update
  script:
  - yarn
  - yarn dist
  artifacts:
    name: "staging_${CI_COMMIT_SHA:0:7}"
    expire_in: 1 week
    paths:
    - dist/

test:
  stage: test
  when: manual
  script:
    - yarn run snapshot
  before_script:
  - apt-get update
  - apt-get install -y wget gnupg
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update
    # Took this dependencies from https://circleci.com/orbs/registry/orb/threetreeslight/puppeteer
  - apt-get install -yq gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
  - apt-get install -y git google-chrome-unstable --no-install-recommends
  - rm -rf /var/lib/apt/lists/*
