image: node:10-slim

stages:
  - build

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf --no-install-recommends
    - rm -rf /var/lib/apt/lists/*
  script:
  - yarn
  - ls /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
  - ldd /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
  - /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome --version
  - /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome --headless
  - yarn dist
  artifacts:
    name: "staging_${CI_COMMIT_SHA:0:7}"
    expire_in: 1 week
    paths:
    - dist/
