image: node:13.8-alpine

stages:
  - build

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  before_script:
    - apk --update add git
  script:
  - ls /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
  - /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome --version
  - ldd /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
  - /builds/miare/design-language/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome --headless
  - yarn
  - yarn dist
  artifacts:
    name: "staging_${CI_COMMIT_SHA:0:7}"
    expire_in: 1 week
    paths:
    - dist/
