image: git.miare.ir:5050/miare/images/node:14.20.1-buster-test

stages:
  - build
  - test

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  before_script:
    - apt-get update
  script:
  - yarn
  - yarn dist
  artifacts:
    name: "staging_${CI_COMMIT_SHA:0:7}"
    expire_in: 1 week
    paths:
    - dist/

test:
  stage: test
  when: manual
  script:
    - yarn run snapshot